name: flutter_swiper
description: The best swiper(carousel) for flutter, with multiple layouts, infinite loop. Compatible with Android & iOS.
version: 1.1.6
homepage: https://github.com/yinxing29/flutter_swiper_copy

dependencies:
  flutter:
    sdk: flutter

  transformer_page_view:
    git:
      url: https://github.com/yinxing29/transformer_page_view_copy.git
      ref: 03ae8b43dfa746beb56a6840cb2f09e106095515

  flutter_page_indicator:
    git:
      url: https://github.com/yinxing29/flutter_page_indicator_copy.git
      ref: 5c6f8e86174d159a43edd803229b32e101a755a9

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.3.0"
  flutter: ">=0.1.4 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
